source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!


platform :ios, '11.0'

target 'Polaris_Example' do
  pod 'Polaris', :path => '../'
  
  target 'Polaris_Tests' do
    inherit! :search_paths
    
    
  end
end

# 忽略版本警告
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
